source "https://rubygems.org"

gem "rails", "~> 8.0.1"      # Rails framework
gem "mongoid"      # MongoDB support
gem "redis"         # Redis for caching
gem "httparty"                # Simplified HTTP requests
gem "puma", ">= 5.0"          # Web server (Puma)
gem "bootsnap", require: false
gem "ostruct"
gem "warning"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude" # Debugging support
end
