version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU30-ubuntu-20.04
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "local@123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    cap_add:
      - SYS_PTRACE
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
      
volumes:
  sqlserver-data:
  redis-data:
