development:
  clients:
    default:
      database: crawler_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
  options:
    log_level: :warn

test:
  clients:
    default:
      database: crawler_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
  options:
    log_level: :warn

production:
  clients:
    default:
      database: crawler_production
      hosts:
        - <%= ENV['MONGODB_URI'] || 'localhost:27017' %>
      options:
        server_selection_timeout: 5
  options:
    log_level: :warn
