name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/SolutionTransparencia.sln
    - name: Build
      run: dotnet build --no-restore ./src/SolutionTransparencia.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos on GitHub Actions
        file: ./lcov.info # or the path to wherever your coverage report is generated
        flags: unittests # optional, and can be any string to categorize coverage reports
        name: codecov-umbrella # optional, name of the uploader
        fail_ci_if_error: true # optional (default = false), specify if CI should fail when Codecov runs into errors
